---
- name: Test connectivity and basic setup on target
  hosts: all
  gather_facts: yes
  tasks:
    - name: Check if we can connect to the target
      ping:

    - name: Ensure the "curl" package is installed
      apt:
        name: curl
        state: present
        update_cache: yes

    - name: Ensure the "package_name" package is installed from group vars
      apt:
        name: "{{ package_name }}"
        state: present
        update_cache: yes

    - name: Incluir tareas de instalación para cada paquete
      include_tasks: tasks_loop.yml
      loop: "{{ package_list }}"

    
